### AddExpense
POST http://localhost:7071/api/AddExpense
Cookie:jwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL3YyLjAiLCJpYXQiOjE2MTQ1ODk4MjksImV4cCI6MTY0NjEyNTgyOSwiYXVkIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwic3ViIjoibXlfYWFkX3N1YmplY3QiLCJ1cG4iOiJ1bm9zZF9leHRlcm5hbG1haWwuY29tI0VYVCNAbXlkaXJlY3Rvcnkub25taWNyb3NvZnQuY29tIiwibmFtZSI6IlVub1NEIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidW5vc2RAZXh0ZXJuYWxtYWlsLmNvbSJ9.eDEiXVVO8u2YCuqjWJ3id8cuWcmDcao1ix5y1ik5nlg

{
    "date": "2021-02-28T00:00:00.000+00:00",
    "payee": "Tesco",
    "amount": {{$randomInt}}.{{$randomInt}},
    "status": "New",
    "type": "Regular",
    "description": "Test expense",
    "account": "Current",
    "tags": "groceries",
    "id": "{{$uuid}}"
}

### GetExpenses
GET http://localhost:7071/api/GetExpenses?account=Current
Cookie:jwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL3YyLjAiLCJpYXQiOjE2MTQ1ODk4MjksImV4cCI6MTY0NjEyNTgyOSwiYXVkIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwic3ViIjoibXlfYWFkX3N1YmplY3QiLCJ1cG4iOiJ1bm9zZF9leHRlcm5hbG1haWwuY29tI0VYVCNAbXlkaXJlY3Rvcnkub25taWNyb3NvZnQuY29tIiwibmFtZSI6IlVub1NEIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidW5vc2RAZXh0ZXJuYWxtYWlsLmNvbSJ9.eDEiXVVO8u2YCuqjWJ3id8cuWcmDcao1ix5y1ik5nlg

> {% client.global.set("expense_id", response.body[0].id); %}

### DeleteExpense
DELETE http://localhost:7071/api/DeleteExpense?account=Current&id={{expense_id}}
Cookie:jwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL3YyLjAiLCJpYXQiOjE2MTQ1ODk4MjksImV4cCI6MTY0NjEyNTgyOSwiYXVkIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwic3ViIjoibXlfYWFkX3N1YmplY3QiLCJ1cG4iOiJ1bm9zZF9leHRlcm5hbG1haWwuY29tI0VYVCNAbXlkaXJlY3Rvcnkub25taWNyb3NvZnQuY29tIiwibmFtZSI6IlVub1NEIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidW5vc2RAZXh0ZXJuYWxtYWlsLmNvbSJ9.eDEiXVVO8u2YCuqjWJ3id8cuWcmDcao1ix5y1ik5nlg

### GetReceiptData
GET http://localhost:7071/api/GetReceiptData
Cookie:jwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL3YyLjAiLCJpYXQiOjE2MTQ1ODk4MjksImV4cCI6MTY0NjEyNTgyOSwiYXVkIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwic3ViIjoibXlfYWFkX3N1YmplY3QiLCJ1cG4iOiJ1bm9zZF9leHRlcm5hbG1haWwuY29tI0VYVCNAbXlkaXJlY3Rvcnkub25taWNyb3NvZnQuY29tIiwibmFtZSI6IlVub1NEIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidW5vc2RAZXh0ZXJuYWxtYWlsLmNvbSJ9.eDEiXVVO8u2YCuqjWJ3id8cuWcmDcao1ix5y1ik5nlg

### GetReceiptUploadSasToken
GET http://localhost:7071/api/GetReceiptUploadSasToken
Cookie:jwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL3YyLjAiLCJpYXQiOjE2MTQ1ODk4MjksImV4cCI6MTY0NjEyNTgyOSwiYXVkIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwic3ViIjoibXlfYWFkX3N1YmplY3QiLCJ1cG4iOiJ1bm9zZF9leHRlcm5hbG1haWwuY29tI0VYVCNAbXlkaXJlY3Rvcnkub25taWNyb3NvZnQuY29tIiwibmFtZSI6IlVub1NEIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidW5vc2RAZXh0ZXJuYWxtYWlsLmNvbSJ9.eDEiXVVO8u2YCuqjWJ3id8cuWcmDcao1ix5y1ik5nlg

### UpdateExpense
PATCH http://localhost:7071/api/UpdateExpense
Cookie:jwtToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwL3YyLjAiLCJpYXQiOjE2MTQ1ODk4MjksImV4cCI6MTY0NjEyNTgyOSwiYXVkIjoiMTExMTExMTEtMTExMS0xMTExLTExMTEtMTExMTExMTExMTExIiwic3ViIjoibXlfYWFkX3N1YmplY3QiLCJ1cG4iOiJ1bm9zZF9leHRlcm5hbG1haWwuY29tI0VYVCNAbXlkaXJlY3Rvcnkub25taWNyb3NvZnQuY29tIiwibmFtZSI6IlVub1NEIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidW5vc2RAZXh0ZXJuYWxtYWlsLmNvbSJ9.eDEiXVVO8u2YCuqjWJ3id8cuWcmDcao1ix5y1ik5nlg

{
    "date": "2020-01-27T00:00:00.000+00:00",
    "payee": "Tesco",
    "amount": {{$randomInt}}.{{$$randomInt}},
    "status": "New",
    "type": "Regular",
    "description": "Test expense updated",
    "account": "Current",
    "tags": "groceries",
    "id": "{{expense_id}}"
}